=== eclipse-csi/otterdog/otterdog/resources/schemas/environment.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "wait_timer": { "type": "integer" },
    "reviewers": {
      "type": "array",
      "items": { "type": "string" }
    },
    "prevent_self_review": { "type": "boolean" },
    "deployment_branch_policy": { "type": "string" },
    "branch_policies": {
      "type": "array",
      "items": { "type": "string" }
    },
    "secrets": {
      "type": "array",
      "items": { "$ref": "environment-secret.json" }
    },
    "variables": {
      "type": "array",
      "items": { "$ref": "environment-variable.json" }
    }
  },

  "required": [ "name" ],
  "additionalProperties": false
}

=== eclipse-csi/otterdog/tests/models/resources/otterdog-environment.json
{
  "name": "linux",
  "wait_timer": 15,
  "reviewers": [
    "@netomi",
    "@OtterdogTest/eclipsefdn-security"
  ],
  "prevent_self_review": true,
  "deployment_branch_policy": "selected",
  "branch_policies": [
    "main",
    "develop/*"
  ],
  "secrets": [
    {
      "name": "ENV-SECRET",
      "value": "1234"
    }
  ],
  "variables": [
    {
      "name": "ENV-VARIABLE",
      "value": "some-value"
    }
  ]
}
