=== eclipse-csi/otterdog/otterdog/resources/schemas/org-code-security-configuration.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "description": { "type": "string" },
    "advanced_security": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "dependency_graph": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "dependency_graph_autosubmit_action": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "dependabot_alerts": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "dependabot_security_updates": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "code_scanning_default_setup": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "secret_scanning": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "secret_scanning_push_protection": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "secret_scanning_delegated_bypass": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "secret_scanning_validity_checks": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "secret_scanning_non_provider_patterns": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "private_vulnerability_reporting": { "type": "string", "enum": ["enabled", "disabled", "not_set"] },
    "enforcement": { "type": "string", "enum": ["enforced", "unenforced"] }
  },

  "required": [ "name" ],
  "additionalProperties": false
}

=== eclipse-csi/otterdog/tests/models/resources/otterdog-org-code-security-configuration.json
{
  "name": "my-config",
  "description": "My code security configuration",
  "advanced_security": "enabled",
  "dependency_graph": "enabled",
  "dependency_graph_autosubmit_action": "enabled",
  "dependabot_alerts": "enabled",
  "dependabot_security_updates": "enabled",
  "code_scanning_default_setup": "enabled",
  "secret_scanning": "enabled",
  "secret_scanning_push_protection": "enabled",
  "secret_scanning_delegated_bypass": "disabled",
  "secret_scanning_validity_checks": "enabled",
  "secret_scanning_non_provider_patterns": "enabled",
  "private_vulnerability_reporting": "enabled",
  "enforcement": "enforced"
}
