=== eclipse-csi/otterdog/otterdog/resources/schemas/repository.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "aliases": {
      "type": "array",
      "items": { "type": "string" }
    },
    "description": { "$ref": "types.json#/$defs/string-or-null"},
    "homepage": { "$ref": "types.json#/$defs/string-or-null"},
    "private": { "type": "boolean" },
    "has_discussions": { "type": "boolean" },
    "has_issues": { "type": "boolean" },
    "has_projects": { "type": "boolean" },
    "has_wiki": { "type": "boolean" },
    "is_template": { "type": "boolean" },
    "template_repository": { "$ref": "types.json#/$defs/string-or-null"},
    "post_process_template_content": {
      "type": "array",
      "items": { "type": "string" }
    },
    "forked_repository": { "$ref": "types.json#/$defs/string-or-null"},
    "fork_default_branch_only": { "type": "boolean" },
    "auto_init": { "type": "boolean" },
    "topics": {
      "type": "array",
      "items": { "type": "string" }
    },
    "default_branch": { "type": "string" },
    "allow_rebase_merge": { "type": "boolean" },
    "allow_merge_commit": { "type": "boolean" },
    "allow_squash_merge": { "type": "boolean" },
    "allow_auto_merge": { "type": "boolean" },
    "delete_branch_on_merge": { "type": "boolean" },
    "allow_update_branch": { "type": "boolean" },
    "squash_merge_commit_title": { "type": "string" },
    "squash_merge_commit_message": { "type": "string" },
    "merge_commit_title": { "type": "string" },
    "merge_commit_message": { "type": "string" },
    "archived": { "type": "boolean" },
    "allow_forking": { "type": "boolean" },
    "web_commit_signoff_required": { "type": "boolean" },
    "immutable_releases_enabled": { "type": "boolean" },
    "secret_scanning": { "type": "string" },
    "secret_scanning_push_protection": { "type": "string" },
    "dependabot_alerts_enabled": { "type": "boolean" },
    "dependabot_security_updates_enabled": { "type": "boolean" },
    "private_vulnerability_reporting_enabled": { "type": "boolean" },

    "code_scanning_default_setup_enabled": { "type": "boolean" },
    "code_scanning_default_query_suite": { "type": "string" },
    "code_scanning_default_languages": {
      "type": "array",
      "items": { "type": "string" }
    },

    "custom_properties": { "$ref": "types.json#/$defs/object-or-null"},

    "gh_pages_build_type": { "type": "string" },
    "gh_pages_source_branch": { "$ref": "types.json#/$defs/string-or-null"},
    "gh_pages_source_path": { "$ref": "types.json#/$defs/string-or-null"},
    "gh_pages_visibility": { "type": "string"},
    "workflows": { "$ref": "repo-workflow-settings.json" },
    "branch_protection_rules": {
      "type": "array",
      "items": { "$ref": "branch-protection-rule.json" }
    },
    "rulesets": {
      "type": "array",
      "items": { "$ref": "repo-ruleset.json"}
    },
    "webhooks": {
      "type": "array",
      "items": { "$ref": "webhook.json" }
    },
    "secrets": {
      "type": "array",
      "items": { "$ref": "repo-secret.json" }
    },
    "variables": {
      "type": "array",
      "items": { "$ref": "repo-variable.json" }
    },
    "environments": {
      "type": "array",
      "items": { "$ref": "environment.json" }
    },
    "team_permissions": {
      "type": "object",
      "patternProperties": {
        ".*": { "$ref": "team-permission.json" }
      },
      "additionalProperties": false
    }
  },

  "required": [ "name", "private" ],
  "additionalProperties": false
}

=== eclipse-csi/otterdog/tests/models/resources/otterdog-repo.json
{
  "aliases": ["oldname"],
  "allow_forking": true,
  "has_wiki": true,
  "web_commit_signoff_required": false,
  "allow_rebase_merge": true,
  "squash_merge_commit_message": "COMMIT_MESSAGES",
  "archived": false,
  "has_projects": true,
  "merge_commit_title": "MERGE_MESSAGE",
  "has_issues": true,
  "private": false,
  "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
  "homepage": null,
  "default_branch": "main",
  "description": null,
  "allow_update_branch": false,
  "allow_squash_merge": true,
  "delete_branch_on_merge": false,
  "name": "otterdog-defaults",
  "allow_merge_commit": true,
  "allow_auto_merge": false,
  "merge_commit_message": "PR_TITLE",
  "immutable_releases_enabled": true,
  "secret_scanning": "enabled",
  "dependabot_alerts_enabled": true,
  "gh_pages_build_type": "legacy",
  "gh_pages_source_path": "/",
  "gh_pages_source_branch": "gh-pages"
}
